# Generated by Django 4.0.4 on 2022-06-06 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_student', models.CharField(max_length=40)),
                ('amount_due', models.FloatField()),
                ('percent_paid', models.FloatField()),
                ('amount_paid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alternance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_student', models.CharField(max_length=40)),
                ('contrat', models.CharField(max_length=10)),
                ('companyName', models.CharField(max_length=30)),
                ('topay_student', models.FloatField()),
                ('topay_company', models.FloatField()),
                ('hire_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('moduleId', models.CharField(max_length=10)),
                ('moduleName', models.CharField(max_length=200)),
                ('moduleDescription', models.CharField(max_length=500)),
                ('credits', models.IntegerField()),
                ('cursus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cursus', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=10)),
                ('id_student', models.CharField(max_length=40)),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('campus', models.CharField(max_length=30)),
                ('person_id', models.CharField(max_length=40)),
                ('group', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
